% Chapter 1

\chapter{Literature Review} % Main chapter title

\label{Chapter1} % For referencing the chapter elsewhere, use \ref{Chapter1} 

\lhead{Chapter 1. \emph{Literature Review}} % This is for the header on each page - perhaps a shortened title

%----------------------------------------------------------------------------------------

\section{Some Descriptive Title}
The first person to consider this really interesting topic was \cite{gandrud2013reproducible}.